### ISSUE TITLE
Interrupt ACL2 (^C) on Windows

### ISSUE THREAD

**Issue by calebegg** [calebegg/proof-pad-classic#9]
ACL2s's technique kind of sucks:

http://acl2s.ccs.neu.edu/acl2s/doc/impl.html#impl_acl2_wrap

Also, when I tried it, it messed with Swing's painting events. It seems to permanently steal focus from Swing.

I tried getting this working with some Stack Overflow advice and C#, but was not successful. I might try again at some point.

**Comment by PeterReid** [comment]
I made a wrapper of my own. It is kind of a heinous thing to do, but it seems to work - I can actually interrupt things successfully now. I don't think it handles shut down very nicely just yet.

https://github.com/PeterReid/proof-pad/tree/master/ctrl-c/ctrlc-windows

ACL2 uses the wrapper's stdout directly. The stdin that goes into the wrapper is treated specially: 0 bytes, which we'd never otherwise use since this is all text, are translated into Ctrl-C commands. Other than that it is just piped over to ACL2.

**Comment by calebegg** [comment]
Peter, you are my hero.
